//
// LoginResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class LoginResult: JSONEncodable {

    /** Indicates whether the login was successful. */
    public var success: Bool?
    /** If there was an error, this field is set. */
    public var errorMessage: String?
    /** The auth token that should be passed to every subsequent api call so\nthat the backend can associate the actions with a given user. */
    public var authToken: String?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["success"] = self.success
        nillableDictionary["errorMessage"] = self.errorMessage
        nillableDictionary["authToken"] = self.authToken
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
