//
// LoginRequestAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class LoginRequestAPI: APIBase {
    
        /**
         
         Login user in the backend
         
         - POST /login
         - When the user is authenticated using services like FB login, the auth\ntokens need to be sent to the backend so that the backend can also\nauthenticate the users.
         - examples: [{contentType=application/json, example={
  "success" : true,
  "authToken" : "aeiou",
  "errorMessage" : "aeiou"
}}]
         
         - parameter auth: (body) Login authentication object, for now contains FB auth.

         - returns: RequestBuilder<LoginResult> 
         */
        public class func loginPost(auth auth: LoginRequest) -> RequestBuilder<LoginResult> {
            let path = "/login"
            let URLString = SwaggerClientAPI.basePath + path
            
            let parameters = auth.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<LoginResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
